title = "App Config"

[server]
port = 8080
enabled = true

[database]
host = "db.example.com"
username = "admin"
password = "secret"
connections = 50

[[users]]
name = "Alice"
roles = ["admin", "user"]

[[users]]
name = "Bob"
roles = ["user"]

[map]
key1 = "value1"
key2 = "value2"